version: '3'
services:
  around-mongodb:
    image: mongo:latest
    env_file:
      - .development.env
    container_name: around-mongodb
    ports:
      - 27017:27017
    volumes:
      - around-mongodb-data:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - app
  api-gateway:
    build:
      context: ./
      dockerfile: ./services/api-gateway/Dockerfile
    env_file:
      - .development.env
    ports:
      - 3001:3001
    restart: always
    container_name: api-gateway
    hostname: api-gateway
    networks:
      - app
  users:
    build:
      context: ./
      dockerfile: ./services/users/Dockerfile
    env_file:
      - .development.env
    restart: always
    container_name: users
    hostname: users
    networks:
      - app
volumes:
  around-mongodb-data:
networks:
  app:
